import { DataSource } from 'typeorm';
import { ServiceNowConnection } from '../../modules/servicenow/entities/servicenow-connection.entity';
import { ServiceNowIncident } from '../../modules/servicenow/entities/servicenow-incident.entity';

export async function seedServiceNowData(dataSource: DataSource, tenantId: number): Promise<void> {
  const serviceNowConnectionRepo = dataSource.getRepository(ServiceNowConnection);
  const serviceNowIncidentRepo = dataSource.getRepository(ServiceNowIncident);

  console.log('\n🎫 Seeding ServiceNow integration data...');

  // ============================================
  // ServiceNow Connection
  // ============================================
  let serviceNowConnection = await serviceNowConnectionRepo.findOne({
    where: { tenantId, instanceUrl: 'https://democompany.service-now.com' },
  });

  if (!serviceNowConnection) {
    serviceNowConnection = serviceNowConnectionRepo.create({
      tenantId,
      name: 'Demo ServiceNow Instance',
      instanceUrl: 'https://democompany.service-now.com',
      accessToken: 'demo_sn_token_encrypted',
      refreshToken: 'demo_sn_refresh_encrypted',
      tokenExpiresAt: new Date(Date.now() + 30 * 60 * 1000), // 30 minutes from now
      instanceId: 'inst_demo_123',
      isActive: true,
      totalIncidentsSynced: 10,
      lastSuccessfulSyncAt: new Date(),
    });
    await serviceNowConnectionRepo.save(serviceNowConnection);
    console.log('✓ Created ServiceNow connection');
  } else {
    console.log('✓ ServiceNow connection already exists');
  }

  // ============================================
  // ServiceNow Incidents
  // ============================================
  const incidentsData = [
    {
      sysId: 'sys_inc_0010234',
      number: 'INC0010234',
      shortDescription: 'Email service outage affecting all users',
      description: 'Microsoft Exchange server unresponsive. Impact: 500+ users unable to send/receive emails.',
      state: 'Resolved',
      stateValue: 6,
      priority: '1 - Critical',
      priorityValue: 1,
      urgency: '1 - High',
      urgencyValue: 1,
      impact: '1 - High',
      impactValue: 1,
      category: 'Infrastructure',
      subcategory: 'Email',
      assignedTo: 'user_sn_001',
      assignedToName: 'John Smith',
      assignmentGroup: 'group_infra_001',
      assignmentGroupName: 'Infrastructure Team',
      caller: 'user_sn_caller_001',
      callerName: 'Jane Doe',
      openedAt: new Date('2026-01-18 07:15:00'),
      resolvedAt: new Date('2026-01-18 10:30:00'),
      closedAt: new Date('2026-01-18 11:00:00'),
      resolutionCode: 'Service Restored',
      resolutionNotes: 'Exchange server restarted. Root cause: memory leak.',
      sysCreatedOn: new Date('2026-01-18 07:15:00'),
      sysUpdatedOn: new Date('2026-01-18 11:00:00'),
      sysCreatedBy: 'system',
      sysUpdatedBy: 'user_sn_001',
    },
    {
      sysId: 'sys_inc_0010567',
      number: 'INC0010567',
      shortDescription: 'CRM system slow performance',
      description: 'Salesforce integration experiencing 5-10 second delays.',
      state: 'Resolved',
      stateValue: 6,
      priority: '2 - High',
      priorityValue: 2,
      urgency: '2 - Medium',
      urgencyValue: 2,
      impact: '2 - Medium',
      impactValue: 2,
      category: 'Application',
      subcategory: 'CRM',
      assignedTo: 'user_sn_002',
      assignedToName: 'Jane Doe',
      assignmentGroup: 'group_app_001',
      assignmentGroupName: 'Application Support',
      caller: 'user_sn_caller_002',
      callerName: 'Mike Wilson',
      openedAt: new Date('2026-01-25 13:45:00'),
      resolvedAt: new Date('2026-01-25 16:20:00'),
      closedAt: new Date('2026-01-25 16:45:00'),
      resolutionCode: 'Configuration Change',
      resolutionNotes: 'API rate limit increased with Salesforce.',
      sysCreatedOn: new Date('2026-01-25 13:45:00'),
      sysUpdatedOn: new Date('2026-01-25 16:45:00'),
      sysCreatedBy: 'system',
      sysUpdatedBy: 'user_sn_002',
    },
    {
      sysId: 'sys_inc_0010789',
      number: 'INC0010789',
      shortDescription: 'Production database connection failures',
      description: 'Application servers unable to connect to production database.',
      state: 'In Progress',
      stateValue: 2,
      priority: '1 - Critical',
      priorityValue: 1,
      urgency: '1 - High',
      urgencyValue: 1,
      impact: '1 - High',
      impactValue: 1,
      category: 'Infrastructure',
      subcategory: 'Database',
      assignedTo: 'user_sn_003',
      assignedToName: 'Mike Wilson',
      assignmentGroup: 'group_db_001',
      assignmentGroupName: 'Database Team',
      caller: 'user_sn_caller_003',
      callerName: 'Sarah Johnson',
      openedAt: new Date('2026-02-01 14:30:00'),
      sysCreatedOn: new Date('2026-02-01 14:30:00'),
      sysUpdatedOn: new Date(),
      sysCreatedBy: 'system',
      sysUpdatedBy: 'user_sn_003',
    },
    {
      sysId: 'sys_inc_0010891',
      number: 'INC0010891',
      shortDescription: 'VPN connectivity issues for remote workers',
      description: 'Multiple remote employees unable to connect to corporate VPN.',
      state: 'Resolved',
      stateValue: 6,
      priority: '3 - Moderate',
      priorityValue: 3,
      urgency: '2 - Medium',
      urgencyValue: 2,
      impact: '2 - Medium',
      impactValue: 2,
      category: 'Network',
      subcategory: 'VPN',
      assignedTo: 'user_sn_004',
      assignedToName: 'Sarah Johnson',
      assignmentGroup: 'group_network_001',
      assignmentGroupName: 'Network Operations',
      caller: 'user_sn_caller_004',
      callerName: 'Tom Brown',
      openedAt: new Date('2026-01-29 08:00:00'),
      resolvedAt: new Date('2026-01-29 09:45:00'),
      closedAt: new Date('2026-01-29 10:00:00'),
      resolutionCode: 'Software Update',
      resolutionNotes: 'VPN concentrator firmware updated.',
      sysCreatedOn: new Date('2026-01-29 08:00:00'),
      sysUpdatedOn: new Date('2026-01-29 10:00:00'),
      sysCreatedBy: 'system',
      sysUpdatedBy: 'user_sn_004',
    },
    {
      sysId: 'sys_inc_0010923',
      number: 'INC0010923',
      shortDescription: 'Printer queue stuck preventing document printing',
      description: 'HR department printers not responding. Print queue shows jobs pending but not processing.',
      state: 'Resolved',
      stateValue: 6,
      priority: '4 - Low',
      priorityValue: 4,
      urgency: '3 - Low',
      urgencyValue: 3,
      impact: '3 - Low',
      impactValue: 3,
      category: 'Hardware',
      subcategory: 'Printer',
      assignedTo: 'user_sn_005',
      assignedToName: 'David Lee',
      assignmentGroup: 'group_desktop_001',
      assignmentGroupName: 'Desktop Support',
      caller: 'user_sn_caller_005',
      callerName: 'Lisa Chen',
      openedAt: new Date('2026-02-01 10:30:00'),
      resolvedAt: new Date('2026-02-01 11:15:00'),
      closedAt: new Date('2026-02-01 11:30:00'),
      resolutionCode: 'Service Restart',
      resolutionNotes: 'Print spooler service restarted. Queue cleared.',
      sysCreatedOn: new Date('2026-02-01 10:30:00'),
      sysUpdatedOn: new Date('2026-02-01 11:30:00'),
      sysCreatedBy: 'system',
      sysUpdatedBy: 'user_sn_005',
    },
    {
      sysId: 'sys_inc_0010945',
      number: 'INC0010945',
      shortDescription: 'Mobile app crashes on Android 14',
      description: 'Users on Android 14 reporting app crashes immediately after login.',
      state: 'In Progress',
      stateValue: 2,
      priority: '2 - High',
      priorityValue: 2,
      urgency: '2 - Medium',
      urgencyValue: 2,
      impact: '2 - Medium',
      impactValue: 2,
      category: 'Application',
      subcategory: 'Mobile App',
      assignedTo: 'user_sn_002',
      assignedToName: 'Jane Doe',
      assignmentGroup: 'group_app_001',
      assignmentGroupName: 'Application Support',
      caller: 'user_sn_caller_006',
      callerName: 'Robert Green',
      openedAt: new Date('2026-02-03 13:00:00'),
      sysCreatedOn: new Date('2026-02-03 13:00:00'),
      sysUpdatedOn: new Date(),
      sysCreatedBy: 'system',
      sysUpdatedBy: 'user_sn_002',
    },
    {
      sysId: 'sys_inc_0010956',
      number: 'INC0010956',
      shortDescription: 'File share permissions incorrect for Finance team',
      description: 'Finance team members unable to access quarterly reports folder. Permission denied errors.',
      state: 'Resolved',
      stateValue: 6,
      priority: '3 - Moderate',
      priorityValue: 3,
      urgency: '2 - Medium',
      urgencyValue: 2,
      impact: '2 - Medium',
      impactValue: 2,
      category: 'Infrastructure',
      subcategory: 'File Server',
      assignedTo: 'user_sn_001',
      assignedToName: 'John Smith',
      assignmentGroup: 'group_infra_001',
      assignmentGroupName: 'Infrastructure Team',
      caller: 'user_sn_caller_007',
      callerName: 'Emily White',
      openedAt: new Date('2026-02-02 08:45:00'),
      resolvedAt: new Date('2026-02-02 09:30:00'),
      closedAt: new Date('2026-02-02 09:45:00'),
      resolutionCode: 'Configuration Change',
      resolutionNotes: 'Active Directory group permissions updated.',
      sysCreatedOn: new Date('2026-02-02 08:45:00'),
      sysUpdatedOn: new Date('2026-02-02 09:45:00'),
      sysCreatedBy: 'system',
      sysUpdatedBy: 'user_sn_001',
    },
    {
      sysId: 'sys_inc_0010967',
      number: 'INC0010967',
      shortDescription: 'Backup job failing for production database',
      description: 'Nightly backup job for main production database failing for past 3 days. Disk space issue suspected.',
      state: 'In Progress',
      stateValue: 2,
      priority: '2 - High',
      priorityValue: 2,
      urgency: '1 - High',
      urgencyValue: 1,
      impact: '1 - High',
      impactValue: 1,
      category: 'Infrastructure',
      subcategory: 'Backup',
      assignedTo: 'user_sn_003',
      assignedToName: 'Mike Wilson',
      assignmentGroup: 'group_db_001',
      assignmentGroupName: 'Database Team',
      caller: 'user_sn_caller_008',
      callerName: 'System Monitor',
      openedAt: new Date('2026-02-03 01:00:00'),
      sysCreatedOn: new Date('2026-02-03 01:00:00'),
      sysUpdatedOn: new Date(),
      sysCreatedBy: 'system',
      sysUpdatedBy: 'user_sn_003',
    },
    {
      sysId: 'sys_inc_0010978',
      number: 'INC0010978',
      shortDescription: 'Office WiFi intermittent disconnections',
      description: 'Multiple employees reporting frequent WiFi disconnections in Building A, 3rd floor.',
      state: 'Resolved',
      stateValue: 6,
      priority: '3 - Moderate',
      priorityValue: 3,
      urgency: '2 - Medium',
      urgencyValue: 2,
      impact: '2 - Medium',
      impactValue: 2,
      category: 'Network',
      subcategory: 'Wireless',
      assignedTo: 'user_sn_004',
      assignedToName: 'Sarah Johnson',
      assignmentGroup: 'group_network_001',
      assignmentGroupName: 'Network Operations',
      caller: 'user_sn_caller_009',
      callerName: 'Mark Davis',
      openedAt: new Date('2026-01-31 14:00:00'),
      resolvedAt: new Date('2026-01-31 16:20:00'),
      closedAt: new Date('2026-01-31 16:30:00'),
      resolutionCode: 'Hardware Replacement',
      resolutionNotes: 'Faulty access point replaced.',
      sysCreatedOn: new Date('2026-01-31 14:00:00'),
      sysUpdatedOn: new Date('2026-01-31 16:30:00'),
      sysCreatedBy: 'system',
      sysUpdatedBy: 'user_sn_004',
    },
  ];

  for (const incidentData of incidentsData) {
    let incident = await serviceNowIncidentRepo.findOne({
      where: { sysId: incidentData.sysId },
    });

    if (!incident) {
      incident = serviceNowIncidentRepo.create({
        ...incidentData,
        connectionId: serviceNowConnection.id,
        tenantId,
      });
      await serviceNowIncidentRepo.save(incident);
      console.log(`✓ Created ServiceNow incident: ${incidentData.number}`);
    } else {
      console.log(`✓ ServiceNow incident already exists: ${incidentData.number}`);
    }
  }

  console.log('✅ ServiceNow data seeded successfully!\n');
}
