/**
 * Audit log action types
 */
export enum AuditAction {
  // Authentication
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  LOGIN_FAILED = 'LOGIN_FAILED',
  PASSWORD_RESET = 'PASSWORD_RESET',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',

  // CRUD operations
  CREATE = 'CREATE',
  READ = 'READ',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',

  // System actions
  EXPORT = 'EXPORT',
  IMPORT = 'IMPORT',
  DOWNLOAD = 'DOWNLOAD',

  // Access control
  ACCESS_GRANTED = 'ACCESS_GRANTED',
  ACCESS_DENIED = 'ACCESS_DENIED',
  ROLE_ASSIGNED = 'ROLE_ASSIGNED',
  ROLE_REVOKED = 'ROLE_REVOKED',

  // Connector actions
  CONNECTOR_CONNECTED = 'CONNECTOR_CONNECTED',
  CONNECTOR_DISCONNECTED = 'CONNECTOR_DISCONNECTED',
  CONNECTOR_TEST = 'CONNECTOR_TEST',
  DATA_INGESTED = 'DATA_INGESTED',

  // Signal actions
  SIGNAL_DETECTED = 'SIGNAL_DETECTED',
  SIGNAL_ACKNOWLEDGED = 'SIGNAL_ACKNOWLEDGED',
  SIGNAL_DISMISSED = 'SIGNAL_DISMISSED',

  // Alert actions
  ALERT_CREATED = 'ALERT_CREATED',
  ALERT_TRIGGERED = 'ALERT_TRIGGERED',
  ALERT_DISMISSED = 'ALERT_DISMISSED',

  // Settings
  SETTINGS_CHANGED = 'SETTINGS_CHANGED',
}
