/**
 * System permissions for fine-grained access control
 */
export enum Permission {
  // User management
  USER_CREATE = 'USER_CREATE',
  USER_READ = 'USER_READ',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',

  // Tenant management
  TENANT_CREATE = 'TENANT_CREATE',
  TENANT_READ = 'TENANT_READ',
  TENANT_UPDATE = 'TENANT_UPDATE',
  TENANT_DELETE = 'TENANT_DELETE',

  // Role management
  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_READ = 'ROLE_READ',
  ROLE_UPDATE = 'ROLE_UPDATE',
  ROLE_DELETE = 'ROLE_DELETE',
  ROLE_ASSIGN = 'ROLE_ASSIGN',

  // Audit logs
  AUDIT_READ = 'AUDIT_READ',
  AUDIT_EXPORT = 'AUDIT_EXPORT',

  // Data connectors
  CONNECTOR_CREATE = 'CONNECTOR_CREATE',
  CONNECTOR_READ = 'CONNECTOR_READ',
  CONNECTOR_UPDATE = 'CONNECTOR_UPDATE',
  CONNECTOR_DELETE = 'CONNECTOR_DELETE',
  CONNECTOR_TEST = 'CONNECTOR_TEST',

  // Weak signals
  SIGNAL_READ = 'SIGNAL_READ',
  SIGNAL_ACKNOWLEDGE = 'SIGNAL_ACKNOWLEDGE',
  SIGNAL_DISMISS = 'SIGNAL_DISMISS',

  // KPI access
  KPI_ORG_HEALTH_READ = 'KPI_ORG_HEALTH_READ',
  KPI_BUSINESS_IMPACT_READ = 'KPI_BUSINESS_IMPACT_READ',
  KPI_TECHNICAL_READ = 'KPI_TECHNICAL_READ',

  // Graph visualization
  GRAPH_READ = 'GRAPH_READ',
  GRAPH_EXPORT = 'GRAPH_EXPORT',

  // Alerts
  ALERT_CREATE = 'ALERT_CREATE',
  ALERT_READ = 'ALERT_READ',
  ALERT_UPDATE = 'ALERT_UPDATE',
  ALERT_DELETE = 'ALERT_DELETE',

  // Settings
  SETTINGS_READ = 'SETTINGS_READ',
  SETTINGS_UPDATE = 'SETTINGS_UPDATE',
}
